version: '3.8'
services:
  testing_db:
    image: postgres:latest
    container_name: testing
    restart: always
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=asdasd
    ports:
      - 5432:5432
    volumes:
      # persist data of container
      - test_db:/var/lib/postgresql/data
      # when starting the container, have a look in the database folder & use the SQL file to seed database
      - ./server/database/:/docker-entrypoint-initdb.d/:ro

volumes:
  test_db:
